apiVersion: v1
kind: Service
metadata:
  name: otc-backend
  labels:
    app: otc-backend
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30081
  type: NodePort
  selector:
    app: otc-backend