apiVersion: apps/v1
kind: Deployment
metadata:
  name: otc-backend
  labels:
    app: otc-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otc-backend
  template:
    metadata:
      labels:
        app: otc-backend
    spec:
      containers:
        - name: otc-backend
          image: yvonnetest/otc-docker-backend-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: DATABASE
              value: "otcDb"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
      restartPolicy: Always