name: otc postman CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #- name: Checkout repository
        #uses: actions/checkout@v4
        #with:
         # path: otc_backend

     # - name: Set up JDK
        #uses: actions/setup-java@v3
        #with:
          #java-version: '21'
          #distribution: 'temurin'

      #- name: build backend
        #uses: actions/checkout@v4
       # uses: convictional/trigger-workflow-and-wait@v1.6.5
        #with:
          #owner: yvonnekw
          #repo: otc_backend
         #path: otc_backend
         # github_token: ${{ secrets.G_PERSONAL_TOKEN }}
         # workflow_file_name: backend-ci.yml
          #ref: postman_test_branch

      - name: Wait for backend to be ready
        run: |
          while ! nc -z localhost 8000; do sleep 1; done

      #- name: Build Spring Boot application
        #run: |
          #cd otc_backend
          #mvn -B package -DskipTests

      #- name: Download backend JAR
        #run: |
          #cd otc_backend
         # curl -LO https://github.com/yvonnekw/otc_backend/releases/latest/download/otc-springboot-backend-image.jar

      #- name: Start backend application
        #run: java -jar otc_backend/target/otc-springboot-backend-image.jar &

      #- name: Wait for backend application to be ready
       # run: |
          #while ! nc -z localhost 8000; do sleep 1; done
      #- name: Wait for backend application to be ready
        #run: |
         # while [[ "$(curl -s -o /dev/null -w '%{http_code}' localhost:8000/actuator/health)" != "200" ]]; do sleep 5; done

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests
        run: newman run https://raw.githubusercontent.com/yvonnekw/otc_backend_api_postman_tests/main/collections/otc.postman_collection.json -e https://raw.githubusercontent.com/yvonnekw/otc_backend_api_postman_tests/main/collections/otc.postman_environment.json --delay-request 1000
