name: otc postman CI - 4

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    services:
      minikube:
        image: gcr.io/k8s-minikube/kicbase:v0.0.30
        options: >-
          --memory=2g
          --cpus=2
        ports:
          - 30080:30080  # NodePort for backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Start Minikube
      run: minikube start --driver=docker

    - name: Configure Kubeconfig
      run: minikube update-context

    - name: Pull Docker images
      run: |
        docker pull yvonnetest/otc-docker-backend-image:latest
        docker pull yvonnetest/otc-vite-react-frontend-image:latest

    - name: Load Docker images into Minikube
      run: |
        minikube image load yvonnetest/otc-docker-backend-image:latest
        minikube image load yvonnetest/otc-vite-react-frontend-image:latest

    - name: Apply PostgreSQL secrets
      run: kubectl apply -f ./k8s/postgres-secret.yaml

    - name: Apply PostgreSQL ConfigMap
      run: kubectl apply -f ./k8s/otc-postgres-configMap.yaml

    - name: Apply PostgreSQL PV
      run: kubectl apply -f ./k8s/postgres-pv.yaml

    - name: Apply PostgreSQL PVC
      run: kubectl apply -f ./k8s/postgres-pvc.yaml

    - name: Apply PostgreSQL Deployment and Service
      run: | 
        kubectl apply -f ./k8s/postgres-deployment.yaml
        kubectl apply -f ./k8s/postgres-service.yaml

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f ./k8s/rabbitmq-deployment.yaml
        kubectl apply -f ./k8s/rabbitmq-service.yaml
        kubectl apply -f ./k8s/otc-backend-deployment.yaml --validate=false
        kubectl expose deployment otc-backend --type=NodePort --port=8000 --target-port=8000 --name=otc-backend-service
        kubectl apply -f ./k8s/combined-ingress.yaml --validate=false
    
    - name: Wait for Spring Boot backend to be ready
      run: |
        kubectl rollout status deployment/otc-backend
        sleep 60  # Increase the delay to ensure the service is up and running

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Install Newman
      run: npm install -g newman

    - name: Check if backend is up
      run: |
        for i in {1..10}; do
          curl -f http://127.0.0.1:30080/actuator/health && break || sleep 10
        done

    - name: Run Newman Tests
      run: |
        newman run https://raw.githubusercontent.com/yvonnekw/otc_backend_api_postman_tests/fix_github_actions/collections/otc-for-ci.postman_collection.json \
         -e https://raw.githubusercontent.com/yvonnekw/otc_backend_api_postman_tests/main/collections/otc.postman_environment.json \
          --global-var "baseUrl=http://127.0.0.1:30080" \
          --delay-request 1000

    - name: Save test results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: postman-test-results
        path: newman/
